# Generated by Django 4.2.5 on 2023-10-16 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coursereview_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_courseenrollment', to='api.course'),
        ),
    ]
