# Generated by Django 4.2.5 on 2023-10-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_enrollmment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='review',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
