# Generated by Django 4.2.5 on 2023-10-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_course_enrolmments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='review_edit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
