# Generated by Django 4.2.5 on 2023-10-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_course_is_advertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolmments_count_edit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
