# Generated by Django 4.2.5 on 2023-10-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_enrolmments_count_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ad_expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
